name: Q3 - Archiver Q3.java

on:
  workflow_dispatch:  
  #push:
    #branches:
      #- main  


jobs:
  archiver-et-pousser:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du dépôt
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Créer Q3_archive_java.txt
      run: |
        echo "Nom et prénom : Aubin Montagne" > Q3_archive_java.txt
        echo "" >> Q3_archive_java.txt
        echo "Contenu de Q3.java :" >> Q3_archive_java.txt
        cat Q3.java >> Q3_archive_java.txt

    - name: Configurer Git
      run: |
        git config --global user.name "AubinMontagne"
        git config --global user.email "aubin.montagne@etu.univ-lehavre.fr"

    - name: Ajouter et committer le nouveau fichier
      run: |
        git add Q3_archive_java.txt
        git commit -m "Ajout de Q3_archive_java.txt via workflow" || echo "Pas de changement à committer"

    - name: Pousser les modifications
      run: git push origin HEAD
