name: Q6 - Archiver Q6.java et générer différences

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main  

jobs:
  archiver-et-diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du dépôt
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Créer l'archive, générer différences et pousser
      run: |
        # Générer timestamp JJ-MM-AAAA-HHMMSS
        DATE=$(date '+%d-%m-%Y-%H%M%S')
        ARCHIVE_FILE="Q6_archive_$DATE.txt"

        # Créer le fichier archive
        echo "Nom et prénom : Aubin Montagne" > "$ARCHIVE_FILE"
        echo "" >> "$ARCHIVE_FILE"
        echo "Contenu de Q6.java :" >> "$ARCHIVE_FILE"
        cat Q6.java >> "$ARCHIVE_FILE"
        echo "" >> "$ARCHIVE_FILE"

        # Ajouter taille en caractères et lignes
        echo "Taille en caractères et lignes :" >> "$ARCHIVE_FILE"
        wc Q6.java >> "$ARCHIVE_FILE"

        # Comparer avec le précédent fichier archive
        PREV_FILE=$(ls Q6_archive_*.txt | grep -v "$ARCHIVE_FILE" | sort | tail -n 1 || echo "")
        if [ -n "$PREV_FILE" ]; then
          diff "$PREV_FILE" "$ARCHIVE_FILE" > Q6_différences.txt || echo "Différences trouvées"
        else
          echo "Aucun fichier précédent pour comparaison" > Q6_différences.txt
        fi

        git config --global user.name "AubinMontagne"
        git config --global user.email "aubin.montagne@etu.univ-lehavre.fr"

        git add "$ARCHIVE_FILE" Q6_différences.txt
        git commit -m "Ajout de $ARCHIVE_FILE et Q6_différences.txt via workflow" || echo "Pas de changement à committer"

        git push origin HEAD
